// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserService.Repository;

#nullable disable

namespace UserService.Repository.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserRoles", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            RolesId = new Guid("c7304655-0810-42f1-8051-710a568b2098"),
                            UsersId = new Guid("80abbca8-664d-4b20-b5de-024705497d4a")
                        },
                        new
                        {
                            RolesId = new Guid("e13e48f4-754f-4ab1-817a-245152b11379"),
                            UsersId = new Guid("80abbca8-664d-4b20-b5de-024705497d4a")
                        },
                        new
                        {
                            RolesId = new Guid("e13e48f4-754f-4ab1-817a-245152b11379"),
                            UsersId = new Guid("86dba8c0-d178-41e7-938c-ed49778fb52a")
                        });
                });

            modelBuilder.Entity("UserService.Entities.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c7304655-0810-42f1-8051-710a568b2098"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("e13e48f4-754f-4ab1-817a-245152b11379"),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("UserService.Entities.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("80abbca8-664d-4b20-b5de-024705497d4a"),
                            Email = "admin@example.com",
                            IsActive = true,
                            Name = "Admin User",
                            PasswordHash = "AQAAAAIAAYagAAAAEGtVOXkmwwc57KzDGVK1Y8M8GCICFLFvDpaDilkYvr48jPPbt1vOxyTeCUCD0s6p+Q==",
                            VerifiedAt = new DateTime(2025, 11, 30, 21, 21, 7, 762, DateTimeKind.Utc).AddTicks(1820)
                        },
                        new
                        {
                            Id = new Guid("84fe1970-e510-45c3-90a8-8e0607d056e9"),
                            Email = "user@example.com",
                            IsActive = true,
                            Name = "Regular User",
                            PasswordHash = "AQAAAAIAAYagAAAAEHP8SZ2ACcbxZChtJd4YrJW3H1hfZYbUpWAeifxw6heZoZpI9PJcs+Ks5S0ul4ryCQ==",
                            VerifiedAt = new DateTime(2025, 11, 30, 21, 21, 7, 762, DateTimeKind.Utc).AddTicks(2063)
                        },
                        new
                        {
                            Id = new Guid("f2b8dd4e-bb69-41ce-8fd6-f213790a460b"),
                            Email = "volchkov@inno.by",
                            IsActive = false,
                            Name = "Anton Volchkov",
                            PasswordHash = "AQAAAAIAAYagAAAAEGzGIA5pP3SUaaSHYI093ON4tjYMcLdcY3MDAXB0CwtQIENCmU8jSxEqRfc4ze8XUg==",
                            VerifiedAt = new DateTime(2025, 11, 30, 21, 21, 7, 762, DateTimeKind.Utc).AddTicks(2068)
                        });
                });

            modelBuilder.Entity("UserRoles", b =>
                {
                    b.HasOne("UserService.Entities.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserService.Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
