// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductService.Repository;

#nullable disable

namespace ProductService.Repository.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20251207214053_UpdateProductSeedData")]
    partial class UpdateProductSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductService.Entities.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Description = "Gadgets and electronic devices",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            Description = "Printed and electronic books",
                            Name = "Books"
                        });
                });

            modelBuilder.Entity("ProductService.Entities.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfLastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Products_CategoryId");

                    b.HasIndex("Name");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Products_UserId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8b007a4c-b9d0-4508-b233-ba47ffeb185f"),
                            CategoryId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            DateOfCreation = new DateTime(2025, 11, 29, 19, 34, 28, 328, DateTimeKind.Utc).AddTicks(9860),
                            DateOfLastUpdate = new DateTime(2025, 11, 29, 19, 34, 28, 328, DateTimeKind.Utc).AddTicks(9830),
                            Description = "Modern cut edge powerfull notebook",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Asus K501-UW",
                            Price = 1000m,
                            UserId = new Guid("80abbca8-664d-4b20-b5de-024705497d4a")
                        },
                        new
                        {
                            Id = new Guid("6a1a626b-8b48-42c5-8107-99a2a0e517fe"),
                            CategoryId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            DateOfCreation = new DateTime(2025, 11, 29, 19, 36, 23, 966, DateTimeKind.Utc).AddTicks(2820),
                            DateOfLastUpdate = new DateTime(2025, 11, 29, 19, 36, 23, 966, DateTimeKind.Utc).AddTicks(2800),
                            Description = "Old low budget notebook",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Samsung RV513",
                            Price = 100m,
                            UserId = new Guid("80abbca8-664d-4b20-b5de-024705497d4a")
                        },
                        new
                        {
                            Id = new Guid("4145bbe3-5e1e-4034-9d54-da63f56c02c3"),
                            CategoryId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            DateOfCreation = new DateTime(2025, 11, 30, 1, 22, 6, 517, DateTimeKind.Utc).AddTicks(6910),
                            DateOfLastUpdate = new DateTime(2025, 11, 30, 1, 22, 6, 517, DateTimeKind.Utc).AddTicks(6910),
                            Description = "A very powerful and modern laptop.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Awesome Laptop",
                            Price = 1299.99m,
                            UserId = new Guid("86dba8c0-d178-41e7-938c-ed49778fb52a")
                        },
                        new
                        {
                            Id = new Guid("560a5138-59b7-43be-aac4-03056c4a27d8"),
                            CategoryId = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            DateOfCreation = new DateTime(2025, 11, 30, 1, 22, 6, 517, DateTimeKind.Utc).AddTicks(6920),
                            DateOfLastUpdate = new DateTime(2025, 11, 30, 1, 22, 6, 517, DateTimeKind.Utc).AddTicks(6920),
                            Description = "A must-read for all .NET developers.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Ultimate Web API Book",
                            Price = 49.99m,
                            UserId = new Guid("86dba8c0-d178-41e7-938c-ed49778fb52a")
                        },
                        new
                        {
                            Id = new Guid("5dae7ef3-f812-457c-b8a4-49cfa9d9fd2a"),
                            CategoryId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            DateOfCreation = new DateTime(2025, 12, 1, 21, 22, 4, 997, DateTimeKind.Utc).AddTicks(1010),
                            DateOfLastUpdate = new DateTime(2025, 12, 1, 21, 22, 4, 997, DateTimeKind.Utc).AddTicks(980),
                            Description = "Два прекрасных экрана по цене одного. AMOLED даёт чёткое, яркое и насыщенное изображение, а E-Ink экономит заряд вашего телефона и позволяет с комфортом читать с него при ярком солнечном свете.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Yotaphone 2",
                            Price = 110m,
                            UserId = new Guid("80abbca8-664d-4b20-b5de-024705497d4a")
                        },
                        new
                        {
                            Id = new Guid("b3774de9-7aa9-447a-91e0-68bad89813d8"),
                            CategoryId = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            DateOfCreation = new DateTime(2025, 12, 7, 21, 8, 41, 834, DateTimeKind.Utc).AddTicks(4470),
                            DateOfLastUpdate = new DateTime(2025, 12, 7, 21, 8, 41, 834, DateTimeKind.Utc).AddTicks(4450),
                            Description = "Классика жанра сай-фай. По этому произведению был снят одноименный фильм. А законы робототехники вот-вот найдут применение.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Я робот - Айзек Азимов",
                            Price = 49m,
                            UserId = new Guid("80abbca8-664d-4b20-b5de-024705497d4a")
                        },
                        new
                        {
                            Id = new Guid("f8e433ff-f6db-4cf5-aa29-a1db7fd9bd18"),
                            CategoryId = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            DateOfCreation = new DateTime(2025, 12, 1, 0, 50, 48, 229, DateTimeKind.Utc).AddTicks(1300),
                            DateOfLastUpdate = new DateTime(2025, 12, 1, 0, 50, 48, 229, DateTimeKind.Utc).AddTicks(1280),
                            Description = "Прекрасная автобиографическая книга о солнечном детстве писателя на греческом острове Корфу. Одна из трилогии.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Сад богов - Джеральд Даррелл",
                            Price = 150m,
                            UserId = new Guid("80abbca8-664d-4b20-b5de-024705497d4a")
                        },
                        new
                        {
                            Id = new Guid("d13254ef-108e-4a22-9c15-f70e7479898c"),
                            CategoryId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            DateOfCreation = new DateTime(2025, 12, 7, 21, 29, 11, 387, DateTimeKind.Utc).AddTicks(5360),
                            DateOfLastUpdate = new DateTime(2025, 12, 7, 21, 29, 11, 387, DateTimeKind.Utc).AddTicks(5350),
                            Description = "Электронный гаджет на основе технологии E-Ink. Предназначен для комфортного чтения электронных книг. У него экономичный режим энергопотребления, которого хватает на неделю работы. Возьми с собой всего Гарри Поттера!",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kindle E-Ink Book",
                            Price = 350m,
                            UserId = new Guid("80abbca8-664d-4b20-b5de-024705497d4a")
                        },
                        new
                        {
                            Id = new Guid("3e03a29f-7328-46be-8475-3d0c93e1d29c"),
                            CategoryId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            DateOfCreation = new DateTime(2025, 12, 1, 3, 4, 47, 796, DateTimeKind.Utc).AddTicks(7900),
                            DateOfLastUpdate = new DateTime(2025, 12, 1, 3, 4, 47, 796, DateTimeKind.Utc).AddTicks(7870),
                            Description = "Легкий мощный ноутбук",
                            IsActive = true,
                            IsDeleted = true,
                            Name = "MacBook Air",
                            Price = 1200m,
                            UserId = new Guid("f2b8dd4e-bb69-41ce-8fd6-f213790a460b")
                        },
                        new
                        {
                            Id = new Guid("76612c72-c934-4a97-8195-78a85badb03e"),
                            CategoryId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            DateOfCreation = new DateTime(2025, 11, 24, 4, 57, 27, 431, DateTimeKind.Utc).AddTicks(7010),
                            DateOfLastUpdate = new DateTime(2025, 11, 24, 4, 57, 27, 431, DateTimeKind.Utc).AddTicks(6980),
                            Description = "Test desc",
                            IsActive = true,
                            IsDeleted = true,
                            Name = "Test Phone",
                            Price = 100m,
                            UserId = new Guid("f2b8dd4e-bb69-41ce-8fd6-f213790a460b")
                        });
                });

            modelBuilder.Entity("ProductService.Entities.Models.Product", b =>
                {
                    b.HasOne("ProductService.Entities.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProductService.Entities.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
